config/routes.rb
Rails.application.routes.draw do
  root 'twitters#index'

  resources :twitters, only: :index

end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  include TwittersHelper

  def index
    @tweets = geo_search(params[:q]) unless params[:q].nil?
    @analyzer = Sentimental.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper
  def distance_of_time_in_words_or_absolute(date)
    date <= 2.days.ago ? date.strftime("%b %d, %Y") : time_ago_in_words(date)
  end
end

app/helpers/twitters_helper.rb
require 'twitter'

module TwittersHelper
  @@client = Twitter::REST::Client.new(Settings.twitter)

  def geo_search(q)
    sf_area = '37.7577,-122.4376,100km'
    @@client.search(q, geocode: sf_area).take(20)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSentiment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/twitters/index.html.erb
<div class="row">
  <%= form_tag(twitters_path('json'), method: "get", id: 'search-form') do |f| %>
    <div class="col-sm-10">
      <input class="form-control input-lg" type="text" name="search-text" id="search-text" placeholder="What are you searching for?">
    </div>
    <div class="col-sm-2">
      <input class="btn btn-primary btn-lg" name="search-button" id="search-button" type="submit" value="Search">
    </div>
  <% end %>
</div>

<div class="search-results" id="search-results"></div>